name: todo
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  easy_localization: ^2.3.3+1
  path_provider: ^1.6.27
  provider: ^4.3.2+3
  sqflite: ^1.3.2+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.8.1

flutter_icons:
  image_path: "assets/images/logo.png"
  android: true
  ios: true

flutter:
  uses-material-design: true

  assets:
    - resource/langs/en-US.json
    - resource/langs/tr-TR.json
